name: Release note logger

on:
  push:
    branches:
      - master
      - staging
      - develop

env:
  REF_MASTER: "refs/heads/master"
  REF_STAGING: "refs/heads/staging"
  REF_DEVELOP: "refs/heads/develop"

defaults:
  runs-on: ubuntu-latest

jobs:
  develop_logger:
    if: ${{ github.ref == REF_DEVELOP}}
    # runs-on: ubuntu-latest
    name: Generates notes for develop commits
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: generate notes
        if: ${{ success() }}
        uses: ./actions/release_notes_generator
        id: gennotes
        with:
          path-to-file: "./actions/release_notes_generator/release.json"
          destination-branch: ${{ env.REF_DEVELOP }}
      - name: commit release notes
        if: ${{ success() }}
        run: |-
          git config --global user.email "release_notes@github.com"
          git config --global user.name "RELEASE-bot"
          git diff --quiet || (git add ./actions/release_notes_generator/release.json && git commit -m "Updated Release notes")
          git checkout -b develop
          git push
  staging_logger:
    if: ${{ github.ref == REF_STAGING }}
    # runs-on: ubuntu-latest
    name: Generates notes for staging commits
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: generate notes
        if: ${{ success() }}
        uses: ./actions/release_notes_generator
        id: gennotes
        with:
          path-to-file: "./actions/release_notes_generator/release.json"
          destination-branch: ${{ env.REF_STAGING }}
          base-branch: ${{ env.REF_DEVELOP }}
      - name: commit release notes
        if: ${{ success() }}
        run: |-
          git config --global user.email "release_notes@github.com"
          git config --global user.name "RELEASE_bot"
          git diff --quiet || (git add ./actions/release_notes_generator/release.json && git commit -m "Updated Release notes")
          git push
  master_logger:
    if: ${{ github.ref == REF_MASTER }}
    # runs-on: ubuntu-latest
    name: Generates notes for master commits
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: generate notes
        if: ${{ success() }}
        uses: ./actions/release_notes_generator
        id: gennotes
        with:
          path-to-file: "./actions/release_notes_generator/release.json"
          destination-branch: ${{ env.REF_MASTER }}
          base-branch: ${{ env.REF_STAGING }}
      - name: commit release notes
        if: ${{ success() }}
        run: |-
          git config --global user.email "release_notes@github.com"
          git config --global user.name "RELEASE_bot"
          git diff --quiet || (git add ./actions/release_notes_generator/release.json && git commit -m "Updated Release notes")
          git push