on:
  push:
    branches:
      - master
      - staging
      - develop

jobs:
    release_gen_job:
        runs-on: ubuntu-latest
        name: A job to generate release notes
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: generate notes
              uses: ./actions/release_notes_generator
              id: gennotes
              with:
                path-to-file: "./actions/release_notes_generator/release.json"
                branch-name: ${{ github.ref }}
            - name: commit release notes
              run: |-
                git config --global user.email "release_notes@github.com"
                git config --global user.name "RELEASE-bot"
                git diff --quiet || (git add ./actions/release_notes_generator/release.json && git commit -m "Updated Release notes")
                git push