on: [push]

jobs:
    release_gen_job:
        runs-on: ubuntu-latest
        name: A job to generate release notes
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: generate notes
              uses: ./
              id: gennotes