name: Release note logger

on:
  push:
    branches:
      - master
      - staging
      - develop

env:
  MASTER: refs/heads/master
  STAGING: refs/heads/staging
  DEVELOP: refs/heads/develop
  MASTER_FILE: ./actions/release_notes_generator/changelogs/master_changelog.json
  STAGING_FILE: ./actions/release_notes_generator/changelogs/staging_changelog.json
  DEVELOP_FILE: ./actions/release_notes_generator/changelogs/develop_changelog.json

jobs:
  develop_logger:
    if: github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest
    name: Develop logger
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Generate release notes
        if: ${{ success() }}
        uses: ./actions/release_notes_generator
        with:
          path-to-file: ${{ env.DEVELOP_FILE }}
          branch-ref: ${{ env.DEVELOP }}
      - name: Commit release notes
        if: ${{ success() }}
        run: |-
          git config --global user.email "release_bot@github.com"
          git config --global user.name "RELEASE_bot"
          git diff --quiet || (git add ${{ env.DEVELOP_FILE }} && git commit -m "Generated release notes")
          git push
  staging_logger:
    if: github.ref == 'refs/heads/staging'
    runs-on: ubuntu-latest
    name: Staging logger
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Generate release notes
        if: ${{ success() }}
        uses: ./actions/release_notes_generator
        with:
          path-to-file: ${{ env.STAGING_FILE }}
          branch-ref: ${{ env.STAGING }}
      - name: Commit release notes
        if: ${{ success() }}
        run: |-
          git config --global user.email "release_bot@github.com"
          git config --global user.name "RELEASE_bot"
          git diff --quiet || (git add ${{ env.DEVELOP_FILE }} && git commit -m "Generated release notes")
          git push
  master_logger:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    name: Master logger
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Generate release notes
        if: ${{ success() }}
        uses: ./actions/release_notes_generator
        with:
          path-to-file: ${{ env.MASTER_FILE }}
          branch-ref: ${{ env.MASTER }}
      - name: Commit release notes
        if: ${{ success() }}
        run: |-
          git config --global user.email "release_bot@github.com"
          git config --global user.name "RELEASE_bot"
          git diff --quiet || (git add ${{ env.DEVELOP_FILE }} && git commit -m "Generated release notes")
          git push