on: [push]

jobs:
    release_gen_job:
        runs-on: ubuntu-latest
        name: A job to generate release notes
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: git log step
              id: gitlog
              run: |
                echo git log --pretty=format:"{%h, %t, %p  - %an, %ae, %ad: %B}" > log.txt
              shell: bash
            - name: generate notes
              uses: ./
              id: gennotes
              with:
                path-to-file: "./.github/workflows/log.txt"